apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: python
  template:
    metadata:
      labels:
        app: python
    spec:
      containers:
        - name: python-app
          image: gcr.io/vois-358709/app
          ports:
            - containerPort: 8000
          env:
            - name: ENVIRONMENT
              value: "DEV"
            - name: HOST
              value: "localhost"
            - name: PORT
              value: "8000"
            - name: REDIS_HOST
              value: redis-service.default.svc.cluster.local     
            - name: REDIS_PORT
              value: "6379"
            - name: REDIS_DB
              value: "0"
